arb-dir: lib/l10n/arb
template-arb-file: app_ru.arb
output-dir: lib/l10n/
output-localization-file: l10n.dart
synthetic-package: false  # Позволяет использовать локализацию напрямую в lib/
nullable-getter: false