name: shelter_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  pair: ^0.1.2
  audioplayers: ^6.4.0
  flutter_svg: ^2.0.17
  dio: ^5.8.0+1
  dart_openai: ^5.1.0
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^3.0.4

flutter:
  generate: true
  uses-material-design: true



  assets:
    - assets/images/door.svg
    - assets/images/hobby.svg
    - assets/images/age.svg
    - assets/images/health.svg
    - assets/images/extra.svg
    - assets/images/phobia.svg
    - assets/images/luggage.svg
    - assets/audio/button_tap.mp3
    - assets/request_texts.json
    - .env
  #   - images/a_dot_ham.jpeg

