name: shelter_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  pair: ^0.1.2
  dio: ^5.8.0+1
  dart_openai: ^5.1.0
  flutter_dotenv: ^5.2.1
  flutter_tts: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^3.0.4

flutter:
  generate: true
  uses-material-design: true



  assets:
    - assets/images/door.png
    - assets/images/hobby.png
    - assets/request_texts.json
    - .env
  #   - images/a_dot_ham.jpeg

