name: Flutter Code Formatter

on:
  push:
    branches: 
     - "main"

jobs:
  formate:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
          distribution: "temurin"
          java-version: "17"
      
    - name: Setup flutter  
      uses: subosito/flutter-action@v2.14.0
      with:
          channel: "stable"
    
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: flutter pub get

    - name: Format
      run: dart format lib

    - name: Check for Changes
      id: git-diff
      run: |
        git diff --quiet || echo "has_changes=true" >> $GITHUB_ENV

    - name: Commit fixes
      if: env.has_changes == 'true'
      run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "chore: auto-format code"
          git push
