name: Flutter Pull Request

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Cache Java
        uses: actions/cache@v4
        with:
          path: |
            ~/.sdkman
          key: java-17-${{ runner.os }}
          restore-keys: |
            java-17-

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: ~/.flutter
          key: flutter-${{ runner.os }}-stable
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          channel: "stable"

      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Create .env file
        run: echo "API_KEY=${{ secrets.API_KEY }}" > .env

  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore Flutter SDK from cache
        uses: actions/cache@v4
        with:
          path: ~/.flutter
          key: flutter-${{ runner.os }}-stable

      - name: Add Flutter to PATH
        run: echo "$HOME/.flutter/bin" >> $GITHUB_PATH

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: flutter-deps-${{ runner.os }}-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            flutter-deps-${{ runner.os }}-

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('android/build.gradle', 'android/app/build.gradle') }}
          restore-keys: |
            gradle-${{ runner.os }}-

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Restore Flutter SDK from cache
        uses: actions/cache@v4
        with:
          path: ~/.flutter
          key: flutter-${{ runner.os }}-stable

      - name: Add Flutter to PATH
        run: echo "$HOME/.flutter/bin" >> $GITHUB_PATH

      - name: Run Flutter tests
        run: flutter test

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Restore Flutter SDK from cache
        uses: actions/cache@v4
        with:
          path: ~/.flutter
          key: flutter-${{ runner.os }}-stable

      - name: Add Flutter to PATH
        run: echo "$HOME/.flutter/bin" >> $GITHUB_PATH

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Apk Release
          path: build/app/outputs/apk/release/app-release.apk
